# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8]
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install nose
        python -m pip install nose_parameterized
        python -m pip install coveralls

    - run: python -m nose -v --with-coverage

    - uses: codecov/codecov-action@v1
